Fixed Vagrant Setup Circuit Sync Issue
Summary: The vagrant setup was being built using the open source code which has not been updated in months. It was causing the deployments to fail. Changes have been made to clone the latest code from the private repository and then sync all the clouds, models and packs when the vagrant is provisioned for the first time.

diff --git a/oneops-packer/vagrant/Vagrantfile b/oneops-packer/vagrant/Vagrantfile
--- a/oneops-packer/vagrant/Vagrantfile
+++ b/oneops-packer/vagrant/Vagrantfile
@@ -26,13 +26,35 @@ Vagrant.configure(2) do |config|
     push.script = "update_war_file.sh"
   end
 
+  # This code will ask for GECGitHub credentials that will be used to clone the private circuit repositories.
+  # It will only run during provisioning phase (first time provisioning or force provisioning)
+  if Dir.glob("#{File.dirname(__FILE__)}/.vagrant/machines/default/*").empty? || ARGV[1] == '--provision'
+    require 'io/console'
+
+    puts "*** Starting Vagrant Provisioning ***"
+    sleep 2
+    puts "\nPlease Provide Your Git Credentials\n\n"
+    print "Username for 'https://gecgithub01.walmart.com': "
+    username = STDIN.gets.chomp
+    print "Password for 'https://gecgithub01.walmart.com': "
+    password = STDIN.noecho(&:gets).chomp
+    puts "\n\n"
+
+    config.vm.provision "run_circuit_install", type: "shell", inline: $script_run_circuit_install, args: [username, password]
+  end
+
   #if you want to sync circuits on your host with vagrant then create an env variable ONEOPS_HOME on your host that points to a directory that houses all the circuits and oneops core
   if !ENV['ONEOPS_HOME'].nil?
     config.vm.synced_folder ENV['ONEOPS_HOME']+"/circuit-oneops-1", "#{sync_folder_root}/circuit-oneops-1",owner: "root",group: "root"
-    config.vm.synced_folder ENV['ONEOPS_HOME']+"/oneops/oneops-admin", "#{sync_folder_root}/oneops-admin",owner: "root",group: "root"
+    config.vm.synced_folder ENV['ONEOPS_HOME']+"/circuit-main-1", "#{sync_folder_root}/circuit-main-1",owner: "root",group: "root"
+    config.vm.synced_folder ENV['ONEOPS_HOME']+"/circuit-walmartlabs-1", "#{sync_folder_root}/circuit-walmartlabs-1",owner: "root",group: "root"
+    config.vm.synced_folder ENV['ONEOPS_HOME']+"/circuit-main-2", "#{sync_folder_root}/circuit-main-2",owner: "root",group: "root"
+    config.vm.synced_folder ENV['ONEOPS_HOME']+"/circuit-walmartlabs-2", "#{sync_folder_root}/circuit-walmartlabs-2",owner: "root",group: "root"
 
+    config.vm.synced_folder ENV['ONEOPS_HOME']+"/oneops/oneops-admin", "#{sync_folder_root}/oneops-admin",owner: "root",group: "root"
+    
     config.vm.provision "configure_circuits", type: "shell", inline: $script_configure_circuits, env: {"sync_folder_root" => sync_folder_root}
-    config.vm.provision "use_latest_inductor", type: "shell", inline: $script_use_latest_inductor, env: {"sync_folder_root" => sync_folder_root}
+		config.vm.provision "use_latest_inductor", type: "shell", inline: $script_use_latest_inductor, env: {"sync_folder_root" => sync_folder_root}
   end
 end
 
@@ -41,7 +63,7 @@ $script_configure_circuits = <<SCRIPT
   cd /opt/oneops/inductor
 
   echo "deleting/unlinking existing circuits"
-  circuits=( circuit-oneops-1 shared )
+  circuits=( circuit-oneops-1 circuit-main-1 circuit-walmartlabs-1 circuit-main-2 circuit-walmartlabs-2 shared )
 
   for circuit in "${circuits[@]}"
   do
@@ -81,4 +103,17 @@ $script_use_latest_inductor = <<SCRIPT
 
   echo "copying latest inductor jar from $sync_folder_root/oneops-admin/target to $oneops_admin_path/target"
   cp "$sync_folder_root/oneops-admin/target"/inductor-*.jar target/
+SCRIPT
+
+# This inline script will call the sync_circuits.sh script inside the vagrant where all the circuits will first get cloned and then synced (model, cloud & pack)
+$script_run_circuit_install = <<SCRIPT
+#!/bin/bash
+
+bash /home/oneops/sync_circuits.sh "$1" "$2"
+
+if [ $? -ne 0 ]
+then
+  echo "Circuit Install Script Failed!"
+  exit 1
+fi
 SCRIPT
